name: Docker Image CI

on: [push]

env:
  NAME: node-minimal

jobs:

  build:
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8, 12]
 
    steps:
     # http://man7.org/linux/man-pages/man1/date.1.html
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash
    - name: ccache cache files
      uses: actions/cache@v2
      with:
        path: .ccache
        key: ${{ matrix.node_version }}-ccache-${{ steps.get-date.outputs.date }}
    - uses: actions/checkout@v2
    - name: Build Node
      run: |
        cd ${{ matrix.node_version }}
        docker build . --file Dockerfile --tag $NAME:${{ matrix.node_version }}
    - name: Test Node
      run: docker run --rm $NAME:${{ matrix.node_version }} -e "console.log('Hello from Node.js ' + process.version)"