name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Build Node
      run: |
        cd 8
        docker build . --file Dockerfile --tag node-minimal:8
    - name: Test Node
      run: docker run --rm node-minimal:8 -e "console.log('Hello from Node.js ' + process.version)"