name: Docker Image CI

on: [push]

env:
  NAME: node-minimal

jobs:

  build:
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12, 14]
 
    steps:
    - uses: actions/checkout@v2
    - name: Build Node
      run: |
        cd ${{ matrix.node_version }}
        docker build . --file Dockerfile --tag $NAME:${{ matrix.node_version }}
    - name: Test Node
      run: docker run --rm $NAME:${{ matrix.node_version }} -e "console.log('Hello from Node.js ' + process.version)"
